language: php
php:
- 5.2
- 5.3
- 5.4
- 5.5
- 5.6
env:
- DB=mysql
before_script:
script: phpunit --configuration phpunit.xml --coverage-text
notifications:
  hipchat: 7f688687a45908cc673458a0e8b968@Quoidautre
before_deploy: "echo 'ready to deploy ?'"
deploy:
  provider: heroku
  api_key:
    secure: dgld53Gp9qjoM9INfR8kJodOC5IgZ1KThh2YiyarLFpp8xxSVdNIDeP9sfAr/anOas9cg7gAYvMRZ1BpetpX3h2WRuAYk232cux0eDHOSAVnR50ANNaHwgWieUC5RYsIvS5kN2FGA8Po9dMNZMij9rQOsb9lFCm7DFO4mWOoGUU=
  app: testing-travis-ci-deployment
  on:
    repo: quoidautre/testing
after_deploy: "echo 'Deployment successfull !'"
